### ISSUE TITLE
 Unable to locate element: //form/span/button[text()='Log in']

### ISSUE THREAD

**Issue by freefrancisman** [converge/InstaPy-Light#5]
I can't log in, script can't find the login button
Message: Unable to locate element: //form/span/button[text()='Log in']

**Comment by converge** [comment]
hello, the project is kind outdated. I'm the only maintainer, so I'll stop updating. but we still have InstaPy.

**Comment by freefrancisman** [comment]
What's the difference between InstaPy and InstaPy Light?

**Comment by converge** [comment]
InstaPy has less features and is built to use Firefox. The code base is shorter, it's easier to maintain.

**Comment by freefrancisman** [comment]
Thanks, I got InstaPy to work
